version: '1'
services:
  app:
    container_name: AuthBack
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
  mongo:
    container_name: AuthDB
    image: mongo:4.2
    restart: always 
    ports:
      - '27017:27017'