version: '3'
services:
  app:
    container_name: AuthBack
    volumes:
      - .:/app
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:15.5-bullseye
    ports: 
      - 5432:5432
    environment:
      POSTGRES_USER: fileuser
      POSTGRES_PASSWORD: Mg71[A~00uk 
      POSTGRES_DB: filedb